server:
  port: 5002
spring:
  application:
    name: "kafka-subscriber-2"
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: tom
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
